// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Device is an attached Android device known to adb.
 */
export class Device {
    /**
     * adb serial (USB serial or ip:port)
     */
    "serial": string;

    /**
     * device | offline | unauthorized
     */
    "state": string;

    /**
     * human model name
     */
    "model": string;

    /**
     * usb | tcpip
     */
    "transport": string;

    /** Creates a new Device instance. */
    constructor($$source: Partial<Device> = {}) {
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("transport" in $$source)) {
            this["transport"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Device instance from a string or object.
     */
    static createFrom($$source: any = {}): Device {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Device($$parsedSource as Partial<Device>);
    }
}

/**
 * FileEntry is one row from an `adb shell ls -la` listing.
 */
export class FileEntry {
    "name": string;
    "path": string;
    "is_dir": boolean;
    "size": number;
    "mod_time": time$0.Time;

    /**
     * permission bits, e.g. "drwxr-xr-x"
     */
    "mode": string;

    /**
     * symlink target, empty if not a link
     */
    "link": string;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("is_dir" in $$source)) {
            this["is_dir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mod_time" in $$source)) {
            this["mod_time"] = null;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("link" in $$source)) {
            this["link"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

export enum TransferDirection {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    DirPush = 0,
    DirPull = 1,
};

export enum TransferState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    StatePending = 0,
    StateActive = 1,
    StateDone = 2,
    StateFailed = 3,
    StateCancelled = 4,
};

/**
 * TransferTask describes one push or pull operation, tracked by the queue.
 */
export class TransferTask {
    "id": string;
    "direction": TransferDirection;
    "state": TransferState;
    "file_name": string;
    "total": number;
    "bytes": number;
    "speed": number;
    "error"?: string;
    "created_at": time$0.Time;
    "done_at"?: time$0.Time | null;

    /** Creates a new TransferTask instance. */
    constructor($$source: Partial<TransferTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = TransferDirection.$zero;
        }
        if (!("state" in $$source)) {
            this["state"] = TransferState.$zero;
        }
        if (!("file_name" in $$source)) {
            this["file_name"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferTask instance from a string or object.
     */
    static createFrom($$source: any = {}): TransferTask {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferTask($$parsedSource as Partial<TransferTask>);
    }
}
