// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Info describes the result of an update check.
 */
export class Info {
    "current_version": string;
    "latest_version": string;
    "has_update": boolean;

    /**
     * raw GitHub URL; proxy applied at download time
     */
    "download_url": string;
    "release_notes": string;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("current_version" in $$source)) {
            this["current_version"] = "";
        }
        if (!("latest_version" in $$source)) {
            this["latest_version"] = "";
        }
        if (!("has_update" in $$source)) {
            this["has_update"] = false;
        }
        if (!("download_url" in $$source)) {
            this["download_url"] = "";
        }
        if (!("release_notes" in $$source)) {
            this["release_notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}
