// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

/**
 * CancelTask cancels a queued or active task.
 */
export function CancelTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(840985698, id);
}

/**
 * ConnectDevice attaches a wireless device by ip:port.
 */
export function ConnectDevice(addr: string): $CancellablePromise<string> {
    return $Call.ByID(3815546895, addr);
}

/**
 * Delete removes a file/dir on the device.
 */
export function Delete(serial: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1990065762, serial, path);
}

/**
 * GetDevices returns currently attached devices.
 */
export function GetDevices(): $CancellablePromise<model$0.Device[]> {
    return $Call.ByID(2647233474).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTasks returns the current transfer queue.
 */
export function GetTasks(): $CancellablePromise<(model$0.TransferTask | null)[]> {
    return $Call.ByID(4294202735).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * HomePath returns the host user home directory (default for local pane).
 */
export function HomePath(): $CancellablePromise<string> {
    return $Call.ByID(3688049421);
}

/**
 * ListDir lists a directory on the given device.
 */
export function ListDir(serial: string, path: string): $CancellablePromise<model$0.FileEntry[]> {
    return $Call.ByID(2120475736, serial, path).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListLocalDir lists a directory on the host machine (the local pane).
 * Returns the same FileEntry shape as the device pane so both render alike.
 */
export function ListLocalDir(dir: string): $CancellablePromise<model$0.FileEntry[]> {
    return $Call.ByID(827505715, dir).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Mkdir creates a directory on the device.
 */
export function Mkdir(serial: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1411813792, serial, path);
}

/**
 * PullFiles downloads one or more remote files/dirs to localDir on the host.
 */
export function PullFiles(serial: string, remotePaths: string[], localDir: string): $CancellablePromise<void> {
    return $Call.ByID(2027259785, serial, remotePaths, localDir);
}

/**
 * PushFiles uploads one or more local files/dirs to remoteDir on the device.
 */
export function PushFiles(serial: string, localPaths: string[], remoteDir: string): $CancellablePromise<void> {
    return $Call.ByID(4180707552, serial, localPaths, remoteDir);
}

/**
 * Rename renames a path on the device.
 */
export function Rename(serial: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(3432540379, serial, oldPath, newPath);
}

// Private type creation functions
const $$createType0 = model$0.Device.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.TransferTask.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = model$0.FileEntry.createFrom;
const $$createType6 = $Create.Array($$createType5);
