// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "./internal/update/models.js";

/**
 * CancelTask cancels a queued or active task.
 */
export function CancelTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(840985698, id);
}

/**
 * CheckUpdate queries GitHub for the latest release and returns whether a newer
 * version exists. The frontend uses this for manual checks; the startup auto-
 * check calls it via autoCheck (below) and emits update:available.
 */
export function CheckUpdate(): $CancellablePromise<update$0.Info | null> {
    return $Call.ByID(586574094).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ConnectDevice attaches a wireless device by ip:port.
 */
export function ConnectDevice(addr: string): $CancellablePromise<string> {
    return $Call.ByID(3815546895, addr);
}

/**
 * Delete removes a file/dir on the device.
 */
export function Delete(serial: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1990065762, serial, path);
}

/**
 * DeleteLocal removes a file or directory (recursively) on the host.
 */
export function DeleteLocal(path: string): $CancellablePromise<void> {
    return $Call.ByID(2381255001, path);
}

/**
 * DownloadUpdate downloads the given GitHub asset URL to a temp file, emitting
 * update:progress events as it goes. On completion it opens the installer and
 * emits update:done; on failure it emits update:error. Runs in a goroutine so
 * the frontend call returns immediately.
 * 
 * Starting a new download cancels any in-flight one (tracked on the App) so the
 * user can't launch two concurrent downloads by retrying mid-stream. Each
 * download gets a generation id; only the latest generation reports errors/
 * completion, so a superseded download stays silent.
 */
export function DownloadUpdate(url: string): $CancellablePromise<void> {
    return $Call.ByID(115027584, url);
}

/**
 * GetDevices returns currently attached devices.
 */
export function GetDevices(): $CancellablePromise<model$0.Device[]> {
    return $Call.ByID(2647233474).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTasks returns the current transfer queue.
 */
export function GetTasks(): $CancellablePromise<(model$0.TransferTask | null)[]> {
    return $Call.ByID(4294202735).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * HomePath returns the host user home directory (default for local pane).
 */
export function HomePath(): $CancellablePromise<string> {
    return $Call.ByID(3688049421);
}

/**
 * ListDir lists a directory on the given device.
 */
export function ListDir(serial: string, path: string): $CancellablePromise<model$0.FileEntry[]> {
    return $Call.ByID(2120475736, serial, path).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListLocalDir lists a directory on the host machine (the local pane).
 * Returns the same FileEntry shape as the device pane so both render alike.
 */
export function ListLocalDir(dir: string): $CancellablePromise<model$0.FileEntry[]> {
    return $Call.ByID(827505715, dir).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * Mkdir creates a directory on the device.
 */
export function Mkdir(serial: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1411813792, serial, path);
}

/**
 * PullFiles downloads one or more remote files/dirs to localDir on the host.
 * The destination is a host path, so filepath.Join (host separator) is correct.
 */
export function PullFiles(serial: string, remotePaths: string[], localDir: string): $CancellablePromise<void> {
    return $Call.ByID(2027259785, serial, remotePaths, localDir);
}

/**
 * PushFiles uploads one or more local files/dirs to remoteDir on the device.
 * Device paths must use "/" as separator on every host, so the destination is
 * joined with path.Join (posix) regardless of the host OS.
 */
export function PushFiles(serial: string, localPaths: string[], remoteDir: string): $CancellablePromise<void> {
    return $Call.ByID(4180707552, serial, localPaths, remoteDir);
}

/**
 * Rename renames a path on the device.
 */
export function Rename(serial: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(3432540379, serial, oldPath, newPath);
}

/**
 * Version returns the running application version (injected at build time, or
 * "dev" in development).
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(2431199839);
}

// Private type creation functions
const $$createType0 = update$0.Info.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.Device.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.TransferTask.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = model$0.FileEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
